// Package repos provides reusable per-repo installation logic for fullsend.
// It decouples the core install flow (scaffold commit, variable/secret writes)
// from CLI concerns (prompts, spinners, flag parsing) so that both the
// interactive CLI and future bulk-install commands can share the same logic.
package repos

import (
	"context"
	"errors"
	"fmt"
	"regexp"

	"github.com/fullsend-ai/fullsend/internal/config"
	"github.com/fullsend-ai/fullsend/internal/forge"
	"github.com/fullsend-ai/fullsend/internal/maputil"
	"github.com/fullsend-ai/fullsend/internal/poll"
	"github.com/fullsend-ai/fullsend/internal/preset"
	"github.com/fullsend-ai/fullsend/internal/scaffold"
)

// WIFProviderPattern validates the full WIF provider resource name format
// required by google-github-actions/auth@v3.
// GCP pool/provider IDs: 4-32 chars, [a-z0-9-], start with letter, no trailing hyphen.
var WIFProviderPattern = regexp.MustCompile(
	`^projects/\d+/locations/global/workloadIdentityPools/[a-z][a-z0-9-]{2,30}[a-z0-9]/providers/[a-z][a-z0-9-]{2,30}[a-z0-9]$`,
)

// InstallConfig is a pure data struct holding all inputs needed for a
// per-repo installation. CLI flags, environment variables, and interactive
// prompts are resolved by the caller before constructing this struct.
type InstallConfig struct {
	Owner string
	Repo  string
	Forge string

	// Roles is the list of agent roles to install (e.g., "triage", "code").
	Roles []string

	MintURL string

	InferenceProject string
	InferenceRegion  string

	// UpstreamRef is the git ref (SHA) used to pin scaffold workflow refs.
	// Empty for dev builds (falls back to config.DefaultUpstreamRef).
	UpstreamRef string
	// UpstreamTag is the version tag corresponding to UpstreamRef (e.g., "v0.42.0").
	UpstreamTag string

	// Skip flags control which install steps are executed. Set by callers
	// that handle specific steps externally (e.g., admin.go handles mint
	// setup before calling Install).
	SkipAppSetup bool

	// SkipScaffoldAndConfig skips scaffold file delivery and variable/secret
	// writes. The caller handles these steps externally (e.g., vendor mode
	// commits scaffold and vendor files together atomically).
	SkipScaffoldAndConfig bool

	// WIFProvider is the pre-computed WIF provider resource name. The caller
	// is responsible for computing or provisioning this value before calling
	// Install. Required unless SkipScaffoldAndConfig is true.
	WIFProvider string

	// PerRepoConfig, when set, overrides the default per-repo config
	// generated by NewPerRepoConfig. Used during migration to carry
	// over org config fields into the per-repo config.
	PerRepoConfig config.PerRepoConfigWriter

	// Runtime, when set, is written as the per-repo `runtime:` of the
	// generated config (`fullsend admin install <owner>/<repo> --runtime`).
	// Empty keeps the code default; ignored when PerRepoConfig is set.
	Runtime string

	// VendorBinary renders scaffold workflows to reference the vendored
	// binary path instead of fetching from upstream on each CI run.
	VendorBinary bool

	// ReviewAppClientID is the OAuth client ID of the review agent's
	// GitHub App. When set, it is written as the FULLSEND_REVIEW_CLIENT_ID
	// repo variable so that pre-fetch-prior-review.sh can validate
	// provenance of prior review comments.
	ReviewAppClientID string

	// AgentRunnerTags is a list of GitLab CI runner tags embedded in the
	// agent job so sandbox work is routed to the data-plane fleet.
	AgentRunnerTags []string

	// ControlRunnerTags is a list of GitLab CI runner tags embedded in
	// control-plane jobs (poll today). Independent of AgentRunnerTags:
	// unset renders an empty (untagged) tag list, not the agent tags.
	ControlRunnerTags []string

	// Direct controls scaffold delivery: true pushes directly to the default
	// branch; false creates a PR.
	Direct bool

	// ReuseSecrets indicates that GCP secrets (FULLSEND_GCP_PROJECT_ID and
	// FULLSEND_GCP_WIF_PROVIDER) already exist on the repo and should not
	// be overwritten. When true, InferenceProject and WIFProvider may be
	// empty and secret writes are skipped.
	ReuseSecrets bool

	// ExistingSecrets lists the repo secret names (e.g.
	// FULLSEND_GCP_PROJECT_ID) already confirmed present on the repo
	// before this install runs. Install skips writing any secret named
	// here individually, so an already-present secret is left untouched
	// even when ReuseSecrets is false because only some of the required
	// secrets exist yet (a partial-secret, workflow-missing re-install —
	// see convergeRepo). ReuseSecrets remains the all-or-nothing signal
	// used for the WIF-provider validation and progress messaging when
	// every required secret already exists.
	ExistingSecrets []string

	// PrebuiltScaffoldFiles, when non-nil, replaces the embedded scaffold
	// template collection. Used when fullsend_ref pins to a version that
	// differs from the running binary, so templates are fetched from the
	// fullsend-ai/fullsend repo at the pinned ref.
	PrebuiltScaffoldFiles scaffold.InstallFiles

	// Preset, when non-nil, is written byte-for-byte as
	// .fullsend/config.base.yaml. The overlay is generated independently
	// unless ManagedConfig is set.
	Preset []byte

	// ManagedConfig, when non-nil, is written as .fullsend/config.yaml
	// instead of generating an installer overlay. Used for config-managed
	// repositories (ADR 0122). Unmanaged repos leave this nil so existing
	// installer generation is preserved.
	ManagedConfig []byte

	// ManagedConfigAdoptionRequired, when true, skips writing
	// .fullsend/config.yaml entirely, even though ManagedConfig may be
	// set: the caller found an existing file that does not carry the
	// ADR-0122 ownership marker, or the pre-write safety gate rejected
	// the candidate, so the file must be left untouched — the same
	// contract convergeManagedConfigFiles enforces on the already-
	// installed path. Callers that do not check for adoption or the
	// safety gate (repos outside the managed-configuration install/
	// converge flow) leave this false so existing behavior is unchanged.
	ManagedConfigAdoptionRequired bool
}

// InstallResult holds the outcome of a per-repo installation.
type InstallResult struct {
	Owner string
	Repo  string

	Success bool
	Error   error

	// WIFProvider is the WIF provider resource name, either pre-existing
	// (from InstallConfig) or newly provisioned.
	WIFProvider string
}

// ScaffoldCommitFunc delivers scaffold files to a repository and returns
// any error encountered.
//
// The installed parameter indicates whether the shim workflow is already
// on the default branch (true = upgrade, false = fresh install). CLI
// implementations use this to select the appropriate commit message, PR
// title, and branch. Fresh-install metadata (DefaultScaffoldBranch) must
// be used until that workflow lands, even if variables or secrets already
// exist from a previous incomplete run.
//
// The CLI layer provides an implementation wrapping layers.CommitScaffoldFiles,
// which adds retry on non-fast-forward errors, branch-protection fallback to
// PR delivery, and fork-based PR support for non-owner users.
type ScaffoldCommitFunc func(ctx context.Context, owner, repo string,
	files []forge.TreeFile, direct bool, installed bool) error

// ProgressFunc is a callback for reporting installation progress. The caller
// maps this to spinner output, structured logs, or whatever UI is appropriate.
//
// Parameters:
//   - repo: the "owner/repo" being installed
//   - phase: a machine-readable phase name (e.g., "scaffold", "vars", "secrets")
//   - message: a human-readable status message
type ProgressFunc func(repo, phase, message string)

// Install performs a per-repo fullsend installation. It generates and commits
// scaffold files, and writes repository
// variables and secrets. The caller is responsible for computing the WIF
// provider resource name (via InstallConfig.WIFProvider) before calling this
// function — GCP provisioning is handled separately by `inference provision`
// and `mint enroll`.
func Install(ctx context.Context, cfg InstallConfig,
	client forge.Client,
	commitScaffold ScaffoldCommitFunc,
	progress ProgressFunc) (*InstallResult, error) {

	if progress == nil {
		progress = func(_, _, _ string) {}
	}

	repoFullName := cfg.Owner + "/" + cfg.Repo
	result := &InstallResult{
		Owner: cfg.Owner,
		Repo:  cfg.Repo,
	}

	mintURL := cfg.MintURL
	if cfg.Forge == ForgeGitHub && mintURL == "" {
		return result, fmt.Errorf("internal error: mint URL not resolved for GitHub repo (public mode should default, private mode should fail validation)")
	}
	wifProvider := cfg.WIFProvider
	result.WIFProvider = wifProvider

	// When SkipScaffoldAndConfig is set, the caller handles scaffold delivery
	// and variable/secret writes externally (e.g., vendor mode commits
	// scaffold and vendor files together atomically via applyPerRepoScaffold).
	if cfg.SkipScaffoldAndConfig {
		result.Success = true
		progress(repoFullName, "done", "Pre-install steps complete")
		return result, nil
	}

	if cfg.InferenceProject != "" && !IsValidGCPProjectID(cfg.InferenceProject) {
		return result, fmt.Errorf("invalid GCP project ID %q", cfg.InferenceProject)
	}
	if cfg.InferenceRegion != "" && !IsValidGCPRegion(cfg.InferenceRegion) {
		return result, fmt.Errorf("invalid GCP region %q", cfg.InferenceRegion)
	}

	// Validate WIF provider when inference secrets will be written.
	if !cfg.ReuseSecrets && cfg.InferenceProject != "" {
		if wifProvider == "" {
			return result, fmt.Errorf("WIF provider required for repository secret configuration; set WIFProvider or enable WIF provisioning")
		}
		if !WIFProviderPattern.MatchString(wifProvider) {
			return result, fmt.Errorf("invalid WIF provider format %q: expected projects/{number}/locations/global/workloadIdentityPools/{pool}/providers/{id}", wifProvider)
		}
	}

	// Step 4: Generate scaffold files.
	progress(repoFullName, "scaffold", "Generating scaffold files")
	files, err := BuildScaffoldFiles(cfg)
	if err != nil {
		return result, fmt.Errorf("generating scaffold files: %w", err)
	}

	// Step 4b: For GitLab, merge fullsend's include and workflow rules
	// into the existing .gitlab-ci.yml instead of overwriting it. The
	// static scaffold skips .gitlab-ci.yml; we generate it dynamically
	// by reading the existing file and merging fullsend entries.
	//
	// When the existing file already contains all fullsend entries,
	// skip the write to avoid unnecessary YAML formatting churn.
	if cfg.Forge == ForgeGitLab {
		existing, err := client.GetFileContent(ctx, cfg.Owner, cfg.Repo, ".gitlab-ci.yml")
		if err != nil && !forge.IsNotFound(err) {
			return result, fmt.Errorf("reading existing .gitlab-ci.yml: %w", err)
		}
		if !HasFullsendEntries(existing) {
			mergedRoot, mergeErr := MergeGitLabCI(existing)
			if mergeErr != nil {
				return result, fmt.Errorf("merging .gitlab-ci.yml: %w", mergeErr)
			}
			files = append(files, forge.TreeFile{
				Path:    ".gitlab-ci.yml",
				Content: mergedRoot,
				Mode:    "100644",
			})
		}
	}

	// Step 5: Write repository variables. Variables and secrets are
	// written before the scaffold commit so the workflow's required
	// secrets exist by the time an event triggers a run. This
	// eliminates the race window described in #6122.
	progress(repoFullName, "vars", "Configuring repository variables")
	repoVars, err := installVarsForForge(cfg, mintURL)
	if err != nil {
		return result, err
	}
	for _, name := range maputil.SortedKeys(repoVars) {
		if err := client.CreateOrUpdateRepoVariable(ctx, cfg.Owner, cfg.Repo, name, repoVars[name]); err != nil {
			return result, fmt.Errorf("setting repo variable %s: %w", name, err)
		}
	}
	progress(repoFullName, "vars", fmt.Sprintf("Set %d repository variables", len(repoVars)))

	// Step 5b: GitLab poll-state branches. Create both HMAC-signed
	// state documents now, seeded from any leftover legacy CI/CD
	// vars, then delete those vars so they are not re-seeded.
	if cfg.Forge == ForgeGitLab {
		progress(repoFullName, "poll-state", "Seeding poll-state branches")
		if err := seedGitLabPollState(ctx, client, cfg.Owner, cfg.Repo); err != nil {
			return result, err
		}
		progress(repoFullName, "poll-state", "Poll-state branches seeded")
		progress(repoFullName, "poll-state", "Retiring legacy poll-state variables")
		for _, a := range retireGitLabLegacyVars(ctx, client, cfg.Owner, cfg.Repo, false, progress) {
			if a.Action == "error" {
				return result, errors.New(a.Detail)
			}
		}
	}

	// Step 6: Write repository secrets. Skipped entirely when reusing all
	// existing secrets; otherwise each secret already present (per
	// ExistingSecrets) is left untouched and only the missing ones are
	// written, so a partial secret state does not get an already-written
	// secret silently retargeted (e.g. by a re-run with a different
	// --inference-project or resolved WIF provider).
	repoSecrets := installSecretsForForge(cfg, wifProvider)
	if cfg.ReuseSecrets {
		progress(repoFullName, "secrets", "Reusing existing repository secrets")
	} else if len(repoSecrets) > 0 {
		existing := make(map[string]bool, len(cfg.ExistingSecrets))
		for _, name := range cfg.ExistingSecrets {
			existing[name] = true
		}
		progress(repoFullName, "secrets", "Configuring repository secrets")
		written := 0
		for _, name := range maputil.SortedKeys(repoSecrets) {
			if existing[name] {
				continue
			}
			if err := client.CreateRepoSecret(ctx, cfg.Owner, cfg.Repo, name, repoSecrets[name]); err != nil {
				return result, fmt.Errorf("setting repo secret %s: %w", name, err)
			}
			written++
		}
		if written > 0 {
			progress(repoFullName, "secrets", fmt.Sprintf("Set %d repository secrets", written))
		}
	}

	// Step 7: Commit scaffold files via the caller-provided commit function.
	// Moved after variable and secret writes to ensure the workflow's
	// required credentials exist before the workflow file goes live.
	progress(repoFullName, "scaffold", "Committing scaffold files")
	if commitErr := commitScaffold(ctx, cfg.Owner, cfg.Repo, files, cfg.Direct, false); commitErr != nil {
		return result, fmt.Errorf("committing scaffold: %w", commitErr)
	}
	progress(repoFullName, "scaffold", "Scaffold files committed")

	result.Success = true
	progress(repoFullName, "done", "Installation complete")
	return result, nil
}

// DriftConfig holds additional fields beyond ResolvedConfig that are
// needed to build a complete InstallConfig for drift detection. These
// fields come from the manifest or CLI flags and are not part of the
// per-repo resolved config.
type DriftConfig struct {
	// InferenceRegion is the GCP region for inference. Only available
	// from CLI flags on repos install; empty on the status path.
	InferenceRegion string

	// ReviewAppClientID is the OAuth client ID of the review agent's
	// GitHub App. Only available from CLI flags on repos install.
	ReviewAppClientID string

	// AgentRunnerTags is a list of GitLab CI runner tags from the
	// manifest's GitLab platform section for agent (data-plane) jobs.
	AgentRunnerTags []string

	// ControlRunnerTags is a list of GitLab CI runner tags from the
	// manifest's GitLab platform section for control-plane jobs. Already
	// resolved through gitlabControlRunnerTags; independent of
	// AgentRunnerTags, so an unset control_runner_tags stays empty here.
	ControlRunnerTags []string
}

// driftInstallConfig constructs the InstallConfig used by both the
// status and converge paths for content drift checking. This is the
// single source of truth for input construction — callers may overlay
// converge-specific fields (resolved ref, PrebuiltScaffoldFiles) on
// the returned value but must not build InstallConfig from scratch.
func driftInstallConfig(resolved ResolvedConfig, dcfg DriftConfig) InstallConfig {
	ref := resolved.FullsendRef
	return InstallConfig{
		Owner:             resolved.Owner,
		Repo:              resolved.Repo,
		Forge:             resolved.Forge,
		Roles:             defaultRoles(nil),
		MintURL:           resolved.MintURL,
		UpstreamRef:       ref,
		UpstreamTag:       ref,
		Runtime:           resolved.Runtime,
		VendorBinary:      resolved.Vendor,
		InferenceRegion:   dcfg.InferenceRegion,
		ReviewAppClientID: dcfg.ReviewAppClientID,
		AgentRunnerTags:   dcfg.AgentRunnerTags,
		ControlRunnerTags: dcfg.ControlRunnerTags,
	}
}

// ExpectedScaffoldContent renders the scaffold files that a fresh install
// would produce for the given resolved config. The status path uses this
// to compare against installed files for content drift detection — when
// the rendered template differs from the installed file, the repo's
// scaffold is stale even if the ref string matches.
//
// When fullsend_ref pins a version that differs from the running binary,
// the refResolver fetches remote scaffold templates from the pinned ref
// so the baseline matches the pinned version, not the embedded templates.
// This mirrors the converge path's FetchRemoteScaffold logic. Both paths
// share driftInstallConfig as the underlying input builder and
// BuildScaffoldFiles as the renderer.
//
// Returns (nil, nil) when FullsendRef is empty — there is no expected
// ref to compare against.
func ExpectedScaffoldContent(ctx context.Context, resolved ResolvedConfig, dcfg DriftConfig, refResolver *RefResolver) ([]forge.TreeFile, error) {
	if resolved.FullsendRef == "" {
		return nil, nil
	}
	installCfg := driftInstallConfig(resolved, dcfg)

	// When the manifest pins a fullsend_ref, fetch remote scaffold
	// templates so the baseline matches the pinned version's templates
	// rather than the running binary's embedded templates. This is the
	// same logic the converge path uses in convergeContentDriftFiles.
	manifestRef := resolved.FullsendRef
	// When vendored, the running binary's embedded templates match the
	// binary being committed to the repo — no version-skew concern, so
	// skip the remote fetch to avoid unnecessary API calls.
	if manifestRef != "" && refResolver != nil && !installCfg.VendorBinary {
		ref := manifestRef
		if isSemver(manifestRef) {
			if sha := refResolver.Resolve(ctx, manifestRef); sha != manifestRef {
				ref = sha
				installCfg.UpstreamRef = ref
			}
		}
		scaffoldFiles, fetchErr := FetchRemoteScaffold(
			ctx, refResolver.client,
			manifestRef, ref, resolved.Forge,
			dcfg.AgentRunnerTags, dcfg.ControlRunnerTags,
			installCfg.VendorBinary,
		)
		if fetchErr == nil {
			installCfg.PrebuiltScaffoldFiles = scaffoldFiles
		}
		// On fetch failure, fall back to embedded templates — same
		// best-effort semantics as the converge path.
	}

	return BuildScaffoldFiles(installCfg)
}

// BuildScaffoldFiles generates the scaffold tree files for a per-repo install.
// Exported so the CLI dry-run path can display the file list without running
// the full install.
func BuildScaffoldFiles(cfg InstallConfig) ([]forge.TreeFile, error) {
	var cfgYAML []byte
	var err error
	if !cfg.ManagedConfigAdoptionRequired {
		if cfg.ManagedConfig != nil {
			cfgYAML = cfg.ManagedConfig
		} else {
			var perRepoCfg config.PerRepoConfigWriter
			switch {
			case cfg.PerRepoConfig != nil:
				perRepoCfg = cfg.PerRepoConfig
			case len(cfg.Preset) > 0:
				// A base preset layer is declared: build a stub overlay with
				// only explicit fleet overrides (mirroring buildPresetOverlay
				// in `github setup --config`), rather than NewPerRepoConfig's
				// full defaults. Layered accessors prefer the overlay over the
				// base, so materializing default roles/allowed_remote_resources/
				// create_issues here would silently shadow the preset's values.
				// cfg.Roles is only non-empty when the caller explicitly
				// requested roles (see defaultRoles in converge.go); an unset
				// Roles here lets the preset (or its own fallback defaults)
				// take effect through the overlay -> base -> code-default chain.
				overlay := config.NewEmptyPerRepoOverlay()
				if len(cfg.Roles) > 0 {
					overlay.SetRoles(cfg.Roles)
				}
				if cfg.Runtime != "" {
					overlay.SetRuntime(cfg.Runtime)
				}
				perRepoCfg = overlay
			default:
				generated := config.NewPerRepoConfig(cfg.Roles, cfg.Owner+"/"+cfg.Repo)
				if cfg.Runtime != "" {
					generated.SetRuntime(cfg.Runtime)
				}
				perRepoCfg = generated
			}
			if err := perRepoCfg.Validate(); err != nil {
				return nil, fmt.Errorf("invalid config: %w", err)
			}
			cfgYAML, err = perRepoCfg.Marshal()
			if err != nil {
				return nil, fmt.Errorf("marshaling config: %w", err)
			}
		}
	}

	var installFiles scaffold.InstallFiles
	if cfg.PrebuiltScaffoldFiles != nil {
		installFiles = cfg.PrebuiltScaffoldFiles
	} else {
		switch cfg.Forge {
		case ForgeGitHub:
			installFiles, err = scaffold.CollectPerRepoInstallFiles(cfg.VendorBinary, cfg.UpstreamRef, cfg.UpstreamTag)
		case ForgeGitLab:
			installFiles, err = scaffold.CollectGitLabPerRepoInstallFiles(cfg.AgentRunnerTags, cfg.ControlRunnerTags, cfg.UpstreamRef, cfg.UpstreamTag)
		default:
			return nil, fmt.Errorf("unsupported forge %q for scaffold generation", cfg.Forge)
		}
		if err != nil {
			return nil, fmt.Errorf("collecting install files: %w", err)
		}
	}

	var files []forge.TreeFile
	for _, f := range installFiles {
		files = append(files, forge.TreeFile{
			Path:    f.Path,
			Content: f.Content,
			Mode:    f.Mode,
		})
	}
	if !cfg.ManagedConfigAdoptionRequired {
		files = append(files, forge.TreeFile{
			Path:    ".fullsend/config.yaml",
			Content: cfgYAML,
			Mode:    "100644",
		})
	}
	if len(cfg.Preset) > 0 {
		plan := preset.Apply(cfg.Preset, nil, nil)
		files = append(files, forge.TreeFile{
			Path:    preset.BasePath,
			Content: plan.Base,
			Mode:    "100644",
		})
	}

	return files, nil
}

// ManagedVar describes a repository variable with its expected value and
// whether it is dynamic (mutated at runtime). Static variables are
// value-checked during drift detection; dynamic variables are
// presence-checked only.
type ManagedVar struct {
	Name    string
	Value   string
	Dynamic bool // true = presence-only (value mutated at runtime)
}

// managedVarsForForge returns the managed variables for a given forge,
// each annotated with whether the variable is dynamic. This is the
// single source of truth for variable classification — callers use the
// Dynamic flag to decide whether to compare values during drift
// detection, without maintaining a separate hardcoded list.
func managedVarsForForge(cfg InstallConfig, mintURL string) ([]ManagedVar, error) {
	switch cfg.Forge {
	case ForgeGitHub:
		vars := []ManagedVar{
			{Name: forge.VarMintURL, Value: mintURL},
		}
		if cfg.InferenceRegion != "" {
			vars = append(vars, ManagedVar{Name: forge.VarGCPRegion, Value: cfg.InferenceRegion})
		}
		if cfg.ReviewAppClientID != "" {
			vars = append(vars, ManagedVar{Name: forge.VarReviewClientID, Value: cfg.ReviewAppClientID})
		}
		return vars, nil
	case ForgeGitLab:
		var vars []ManagedVar
		if cfg.InferenceRegion != "" {
			vars = append(vars, ManagedVar{Name: forge.VarGCPRegion, Value: cfg.InferenceRegion})
		}
		return vars, nil
	default:
		return nil, fmt.Errorf("unsupported forge %q for variable configuration", cfg.Forge)
	}
}

// staticExpectedVarValues returns a map of variable names to expected
// values for all static (non-dynamic) managed variables. This is used
// by the converge and status discovery phases to pass expected values
// to ProbeComponents for value-level drift detection.
func staticExpectedVarValues(cfg InstallConfig, mintURL string) (map[string]string, error) {
	managed, err := managedVarsForForge(cfg, mintURL)
	if err != nil {
		return nil, err
	}
	vals := make(map[string]string)
	for _, v := range managed {
		if !v.Dynamic && v.Value != "" {
			vals[v.Name] = v.Value
		}
	}
	return vals, nil
}

func installVarsForForge(cfg InstallConfig, mintURL string) (map[string]string, error) {
	managed, err := managedVarsForForge(cfg, mintURL)
	if err != nil {
		return nil, err
	}
	vars := make(map[string]string, len(managed))
	for _, v := range managed {
		vars[v.Name] = v.Value
	}
	return vars, nil
}

// installSecretsForForge returns the inference secrets to write.
// Returns nil when InferenceProject is not set (the convergence
// layer validates that InferenceProject is provided for repos
// without existing secrets).
func installSecretsForForge(cfg InstallConfig, wifProvider string) map[string]string {
	if cfg.InferenceProject == "" {
		return nil
	}

	return map[string]string{
		forge.SecretGCPProjectID:   cfg.InferenceProject,
		forge.SecretGCPWIFProvider: wifProvider,
	}
}

// requiredVariables lists the per-repo variables that must exist for a
// complete installation. FULLSEND_GCP_REGION is excluded because it is
// conditionally set (only when --inference-region is provided) and may
// not be present when secrets are reused. Shared by install,
// checkInstallComponents, and uninstall.
var requiredVariables = []string{forge.VarMintURL}

// requiredSecrets lists the per-repo secrets that must exist for a
// complete installation. Shared by install, checkInstallComponents,
// and uninstall.
var requiredSecrets = []string{forge.SecretGCPProjectID, forge.SecretGCPWIFProvider}

// gitlabRetiredLegacyVars is the set of GitLab poller CI/CD variables
// superseded by HMAC-signed state.json on fullsend-poll-state-slash
// and fullsend-poll-state-events. Distinct from the active managed
// set: install does not seed them, CheckOrphanVars treats them as
// known-retired (no spurious warnings), and converge migrate-then-
// deletes any that are still present.
var gitlabRetiredLegacyVars = []string{
	forge.VarLastPollAtFast, forge.VarLastPollAtFull, forge.VarLabelState,
	forge.VarDispatchedKeysFast, forge.VarDispatchedKeysFull,
	forge.VarFailedKeysFast, forge.VarFailedKeysFull,
}

// gitlabPollStateBranches are the two HMAC-signed poll-state branches
// created at install/converge. They are managed git refs, not scaffold
// files on the default branch, so orphan-file detection never sees
// them; any future orphan-branch detector must treat this set as
// known-managed.
var gitlabPollStateBranches = []string{
	poll.PollStateBranchSlash,
	poll.PollStateBranchEvents,
}

// seedGitLabPollState provisions FULLSEND_DISPATCH_SECRET if missing
// and creates both poll-state branches with HMAC-signed state.json,
// migrating any present legacy CI/CD variables. Idempotent: existing
// signed documents are left untouched.
func seedGitLabPollState(ctx context.Context, client forge.Client, owner, repo string) error {
	secret, _, err := poll.EnsureDispatchSecret(ctx, client, owner, repo)
	if err != nil {
		return fmt.Errorf("provisioning dispatch secret: %w", err)
	}
	if _, err := poll.SeedGitLabPollStateBranches(ctx, client, owner, repo, secret); err != nil {
		return fmt.Errorf("seeding poll-state branches: %w", err)
	}
	return nil
}

// retireGitLabLegacyVars migrates still-present retired poll-state
// CI/CD variables into the branch-backed store (if the branches are
// missing) and then deletes the variables. Idempotent: a repo whose
// retired vars are already gone is a no-op. Dry-run reports the
// deletions without writing.
func retireGitLabLegacyVars(ctx context.Context, client forge.Client, owner, repo string, dryRun bool, progress ProgressFunc) []ComponentAction {
	repoFullName := owner + "/" + repo
	vars, err := client.ListRepoVariables(ctx, owner, repo)
	if err != nil {
		return []ComponentAction{{
			Component: "variables",
			Action:    "error",
			Detail:    fmt.Sprintf("listing variables to retire legacy poll state: %v", err),
		}}
	}

	var present []string
	for _, name := range gitlabRetiredLegacyVars {
		if _, ok := vars[name]; ok {
			present = append(present, name)
		}
	}
	if len(present) == 0 {
		return nil
	}

	if dryRun {
		var actions []ComponentAction
		for _, name := range present {
			actions = append(actions, ComponentAction{
				Component: "var:" + name,
				Action:    "delete",
				Detail:    fmt.Sprintf("would migrate then delete retired variable %s", name),
			})
			progress(repoFullName, "dry-run", fmt.Sprintf("Would migrate then delete retired variable %s", name))
		}
		return actions
	}

	if err := seedGitLabPollState(ctx, client, owner, repo); err != nil {
		return []ComponentAction{{
			Component: "poll-state",
			Action:    "error",
			Detail:    fmt.Sprintf("migrating retired poll-state variables into branches: %v", err),
		}}
	}

	var actions []ComponentAction
	for _, name := range present {
		if err := client.DeleteRepoVariable(ctx, owner, repo, name); err != nil {
			actions = append(actions, ComponentAction{
				Component: "var:" + name,
				Action:    "error",
				Detail:    fmt.Sprintf("failed to delete retired variable %s: %v", name, err),
			})
			continue
		}
		actions = append(actions, ComponentAction{
			Component: "var:" + name,
			Action:    "delete",
			Detail:    fmt.Sprintf("migrated then deleted retired variable %s", name),
		})
		progress(repoFullName, "sync", fmt.Sprintf("Deleted retired variable %s", name))
	}
	return actions
}

func requiredVarsForForge(forgeName string) []string {
	if forgeName == ForgeGitLab {
		// GitLab poller state lives on poll-state branches, not CI/CD
		// variables. There are no required GitLab variables.
		return nil
	}
	return requiredVariables
}

// requiredSecretsForForge returns the secret names that must exist for the
// given forge. GitLab runtime authentication is role-credential-only; role
// readiness is checked by the GitLab role registry/status path.
func requiredSecretsForForge(forgeName string) []string {
	return requiredSecrets
}

// checkInstallComponents verifies that all per-repo installation
// components are present (and, when expectedVarValues is provided,
// that variable values match). Returns true only when every component
// matches.
func checkInstallComponents(ctx context.Context, client forge.Client, owner, repo, forgeName string, fc ForgeConfig, expectedVarValues map[string]string) (bool, error) {
	components, err := ProbeComponents(ctx, client, owner, repo, forgeName, fc, expectedVarValues)
	if err != nil {
		return false, err
	}
	return AllMatch(components), nil
}
